# Generated by Django 4.2.30 on 2026-08-24 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codfacturar', models.CharField(help_text='Código del proveedor (ordenesrd.codfacturar) al que va a quedar ligada esta cuenta.', max_length=20)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.CharField(blank=True, max_length=50)),
                ('usada', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Invitación de proveedor',
                'verbose_name_plural': 'Invitaciones de proveedores',
                'db_table': 'portal_proveedor_invitaciones',
            },
        ),
        migrations.CreateModel(
            name='ProveedorPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codfacturar', models.CharField(db_index=True, max_length=20)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedorperfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de proveedor',
                'verbose_name_plural': 'Perfiles de proveedores',
                'db_table': 'portal_proveedor_perfiles',
            },
        ),
    ]
