# Generated by Django 4.2.30 on 2026-09-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedorinvitacion",
            name="codtipmed",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="proveedorinvitacion",
            name="codtsubmed",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="proveedorperfil",
            name="codtipmed",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="proveedorperfil",
            name="codtsubmed",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
