# Generated by Django 4.2.30 on 2026-08-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCodificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyorden', models.IntegerField(db_index=True, help_text='FK lógica hacia ordenesrd.keyorden (1 a 1: una factura, un estado de codificación).', unique=True)),
                ('orden', models.CharField(db_index=True, max_length=20)),
                ('numfactura', models.CharField(max_length=50)),
                ('fecha_codificacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Codificación de factura de proveedor',
                'verbose_name_plural': 'Codificaciones de facturas de proveedor',
                'db_table': 'facturas_proveedor_codificacion',
            },
        ),
    ]
