# Generated by Django 4.2.30 on 2026-08-04 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_facturacodificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('criterio', models.CharField(choices=[('presupuesto', 'Presupuesto'), ('cliente', 'Cliente'), ('marca', 'Marca'), ('tipomedio', 'Tipo de medio')], max_length=20)),
                ('valor_agrupador', models.CharField(help_text='El código agrupado (ej. el codpresup, codcli, codmar o codtipmed específico).', max_length=50)),
                ('codpai', models.CharField(max_length=10)),
                ('codagencia', models.CharField(max_length=20)),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Liquidación de cliente',
                'verbose_name_plural': 'Liquidaciones de clientes',
                'db_table': 'facturas_proveedor_liquidaciones',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyorden', models.IntegerField(db_index=True)),
                ('orden', models.CharField(max_length=20)),
                ('numfactura', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturas.liquidacion')),
            ],
            options={
                'verbose_name': 'Detalle de liquidación',
                'verbose_name_plural': 'Detalles de liquidación',
                'db_table': 'facturas_proveedor_liquidaciones_detalle',
            },
        ),
    ]
