# Generated by Django 4.2.30 on 2026-08-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturas", "0003_liquidacion_liquidaciondetalle"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenCompraAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.CharField(
                        db_index=True,
                        help_text="Número de orden de compra (ordenes.orden).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("archivo", models.FileField(upload_to="ordenes_compra/%Y/%m/")),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("tamano_bytes", models.PositiveIntegerField(default=0)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                ("usuario", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Adjunto de orden de compra",
                "verbose_name_plural": "Adjuntos de órdenes de compra",
                "db_table": "facturas_proveedor_ordenes_compra_adjuntos",
            },
        ),
        migrations.CreateModel(
            name="PresupuestoAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codpresup",
                    models.CharField(
                        db_index=True,
                        help_text="Código del presupuesto (ordenesrd.codpresup / ordenes.codpresup).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("archivo", models.FileField(upload_to="presupuestos/%Y/%m/")),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("tamano_bytes", models.PositiveIntegerField(default=0)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                ("usuario", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Adjunto de presupuesto",
                "verbose_name_plural": "Adjuntos de presupuestos",
                "db_table": "facturas_proveedor_presupuestos_adjuntos",
            },
        ),
    ]
