# Generated by Django 4.2.30 on 2026-08-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturas", "0004_ordencompraadjunto_presupuestoadjunto"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacion",
            name="anulada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="liquidacion",
            name="fecha_anula",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="liquidacion",
            name="motivo_anula",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="liquidacion",
            name="usuario_anula",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
