# Generated by Django 4.2.30 on 2026-09-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturas", "0005_liquidacion_anulada_liquidacion_fecha_anula_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordencompraadjunto",
            name="archivo",
            field=models.FileField(upload_to="OrdenesPdf/"),
        ),
        migrations.AlterField(
            model_name="presupuestoadjunto",
            name="archivo",
            field=models.FileField(upload_to="presupuestos/"),
        ),
    ]
