# Generated by Django 4.2.30 on 2026-09-01 03:22

from django.db import migrations, models
import facturas.models


class Migration(migrations.Migration):
    dependencies = [
        ("facturas", "0006_alter_ordencompraadjunto_archivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordencompraadjunto",
            name="archivo",
            field=models.FileField(
                storage=facturas.models.AlmacenamientoSobrescribible(),
                upload_to="OrdenesPdf/",
            ),
        ),
        migrations.AlterField(
            model_name="presupuestoadjunto",
            name="archivo",
            field=models.FileField(
                storage=facturas.models.AlmacenamientoSobrescribible(),
                upload_to="presupuestos/",
            ),
        ),
    ]
